import { defineConfig } from "drizzle-kit";
import fs from "fs";
import path from "path";

// Dynamically locate the SQLite database file generated by Miniflare/Wrangler
function getLocalSqlitePath() {
  const fallback = ".wrangler/state/v3/d1/miniflare-D1DatabaseObject/b64b34fe1f4e24fbba47549a0d8c225aac6b11d3624f15497ec0bf8eab9c5c62.sqlite";
  try {
    const targetDir = path.join(process.cwd(), ".wrangler", "state", "v3", "d1", "miniflare-D1DatabaseObject");
    if (fs.existsSync(targetDir)) {
      const files = fs.readdirSync(targetDir);
      const dbFile = files.find((f) => f.endsWith(".sqlite"));
      if (dbFile) {
        return path.join(".wrangler", "state", "v3", "d1", "miniflare-D1DatabaseObject", dbFile);
      }
    }
  } catch (_) {
    // Ignore and return fallback
  }
  return fallback;
}

export default defineConfig({
  schema: "./src/server/db/schema.js",
  out: "./migrations",
  dialect: "sqlite",
  dbCredentials: {
    url: getLocalSqlitePath(),
  },
});

